/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KurumsalRouteImport } from './routes/kurumsal'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as OdemeIndexRouteImport } from './routes/odeme/index'
import { Route as UrunlerIndexRouteImport } from './routes/urunler/index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler/$slug'
import { Route as YasalSlugRouteImport } from './routes/yasal/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KurumsalRoute = KurumsalRouteImport.update({
  id: '/kurumsal',
  path: '/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OdemeIndexRoute = OdemeIndexRouteImport.update({
  id: '/odeme/',
  path: '/odeme/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerIndexRoute = UrunlerIndexRouteImport.update({
  id: '/urunler/',
  path: '/urunler/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const YasalSlugRoute = YasalSlugRouteImport.update({
  id: '/yasal/$slug',
  path: '/yasal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/yasal/$slug': typeof YasalSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/odeme/': typeof OdemeIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/yasal/$slug': typeof YasalSlugRoute
  '/blog': typeof BlogIndexRoute
  '/odeme': typeof OdemeIndexRoute
  '/urunler': typeof UrunlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iletisim': typeof IletisimRoute
  '/kurumsal': typeof KurumsalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sepet': typeof SepetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/yasal/$slug': typeof YasalSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/odeme/': typeof OdemeIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/iletisim'
    | '/kurumsal'
    | '/robots.txt'
    | '/sepet'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/urunler/$slug'
    | '/yasal/$slug'
    | '/blog/'
    | '/odeme/'
    | '/urunler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iletisim'
    | '/kurumsal'
    | '/robots.txt'
    | '/sepet'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/urunler/$slug'
    | '/yasal/$slug'
    | '/blog'
    | '/odeme'
    | '/urunler'
  id:
    | '__root__'
    | '/'
    | '/iletisim'
    | '/kurumsal'
    | '/robots.txt'
    | '/sepet'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/urunler/$slug'
    | '/yasal/$slug'
    | '/blog/'
    | '/odeme/'
    | '/urunler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IletisimRoute: typeof IletisimRoute
  KurumsalRoute: typeof KurumsalRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SepetRoute: typeof SepetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UrunlerSlugRoute: typeof UrunlerSlugRoute
  YasalSlugRoute: typeof YasalSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  OdemeIndexRoute: typeof OdemeIndexRoute
  UrunlerIndexRoute: typeof UrunlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurumsal': {
      id: '/kurumsal'
      path: '/kurumsal'
      fullPath: '/kurumsal'
      preLoaderRoute: typeof KurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odeme/': {
      id: '/odeme/'
      path: '/odeme'
      fullPath: '/odeme/'
      preLoaderRoute: typeof OdemeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/': {
      id: '/urunler/'
      path: '/urunler'
      fullPath: '/urunler/'
      preLoaderRoute: typeof UrunlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yasal/$slug': {
      id: '/yasal/$slug'
      path: '/yasal/$slug'
      fullPath: '/yasal/$slug'
      preLoaderRoute: typeof YasalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IletisimRoute: IletisimRoute,
  KurumsalRoute: KurumsalRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SepetRoute: SepetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  UrunlerSlugRoute: UrunlerSlugRoute,
  YasalSlugRoute: YasalSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  OdemeIndexRoute: OdemeIndexRoute,
  UrunlerIndexRoute: UrunlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
